"""
Data Quality Reporter
Generates formatted DQ reports.
"""

import json
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

from config import REPORTS_DIR


class DQReporter:
    """Reporter for data quality results."""
    
    def __init__(self, output_dir: Path = None):
        self.output_dir = output_dir or REPORTS_DIR / "dq"
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def generate_report(self, dq_results: Dict[str, Any]) -> str:
        """
        Generate a formatted DQ report.
        
        Args:
            dq_results: Results from DQEngine
            
        Returns:
            Path to generated report file
        """
        report_date = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
        report_path = self.output_dir / f"dq_report_{report_date}.md"
        
        report_md = self._format_markdown(dq_results)
        
        with open(report_path, "w") as f:
            f.write(report_md)
        
        # Also save as JSON
        json_path = self.output_dir / f"dq_report_{report_date}.json"
        with open(json_path, "w") as f:
            json.dump(dq_results, f, indent=2, default=str)
        
        return str(report_path)
    
    def _format_markdown(self, results: Dict[str, Any]) -> str:
        """Format results as markdown."""
        lines = [
            "# Data Quality Report",
            "",
            f"**Generated:** {results['executed_at']}",
            f"**Overall Score:** {results['dq_score']}/100",
            f"**Status:** {self._status_emoji(results['status'])} {results['status']}",
            f"**Execution Time:** {results['execution_time_seconds']}s",
            "",
            "## Summary",
            "",
            f"- **Total Checks:** {results['checks_run']}",
            f"- **Passed:** {results['checks_passed']} [PASS]",
            f"- **Warnings:** {results['checks_warning']} [WARN]",
            f"- **Failed:** {results['checks_failed']} [FAIL]",
            "",
            "## Results by Table",
            "",
        ]
        
        # Group by table
        by_table = {}
        for result in results['results']:
            table = result['table']
            if table not in by_table:
                by_table[table] = []
            by_table[table].append(result)
        
        for table, checks in by_table.items():
            lines.extend([
                f"### {table}",
                "",
                "| Check | Status | Severity | Metric | Threshold | Details |",
                "|-------|--------|----------|--------|-----------|---------|",
            ])
            
            for check in checks:
                status_emoji = self._status_emoji(check['status'])
                metric_val = f"{check['metric_value']:.2%}" if isinstance(check['metric_value'], float) and check['metric_value'] <= 1 else f"{check['metric_value']:.2f}"
                threshold = f"{check['threshold']:.2%}" if isinstance(check['threshold'], float) and check['threshold'] <= 1 else str(check['threshold'])
                
                lines.append(
                    f"| {check['check_name']} | {status_emoji} {check['status']} | "
                    f"{check['severity']} | {metric_val} | {threshold} | {check['details']} |"
                )
            
            lines.append("")
        
        # Critical issues section
        critical_failures = [r for r in results['results'] if r['status'] == 'FAIL' and r['severity'] == 'CRITICAL']
        if critical_failures:
            lines.extend([
                "## Critical Issues",
                "",
                "The following critical issues require immediate attention:",
                "",
            ])
            
            for issue in critical_failures:
                lines.extend([
                    f"### {issue['table']} - {issue['check_name']}",
                    "",
                    f"- **Details:** {issue['details']}",
                    f"- **Affected Rows:** {issue['affected_rows']} / {issue['total_rows']}",
                    "",
                ])
        
        lines.extend([
            "---",
            "",
            "*This report was automatically generated by the Marketing Data Pipeline.*",
        ])
        
        return "\n".join(lines)
    
    def _status_emoji(self, status: str) -> str:
        """Get emoji for status."""
        return {"PASS": "[PASS]", "WARNING": "[WARN]", "FAIL": "[FAIL]"}.get(status, "[?]")
    
    def generate_summary(self, results: Dict[str, Any]) -> str:
        """Generate a brief text summary."""
        return (
            f"DQ Score: {results['dq_score']}/100 | "
            f"Status: {results['status']} | "
            f"Passed: {results['checks_passed']}/{results['checks_run']}"
        )
